// <auto-generated />
using System;
using A_DAL.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A_DAL.Migrations
{
    [DbContext(typeof(ThuVienContext))]
    [Migration("20231120035341_ThietHai")]
    partial class ThietHai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("A_DAL.Model.NhanVien", b =>
                {
                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("idNhanVien");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hoTen");

                    b.Property<string>("IdTaiKhoan")
                        .HasColumnType("varchar(13)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("soDienThoai");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trangThai");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("A_DAL.Model.TaiKhoan", b =>
                {
                    b.Property<string>("IdTaiKhoan")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("idTaiKhoan");

                    b.Property<string>("IdNhanVien")
                        .HasColumnType("varchar(13)");

                    b.Property<string>("PassWord")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("passWord");

                    b.Property<int?>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userName");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("A_DAL.Model.ThietHai", b =>
                {
                    b.Property<string>("IdThietHai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idThietHai");

                    b.Property<int?>("DiemTruUyTin")
                        .HasColumnType("int")
                        .HasColumnName("diemTruUyTin");

                    b.Property<string>("TenThietHai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenThietHai");

                    b.HasKey("IdThietHai");

                    b.ToTable("ThietHai");
                });

            modelBuilder.Entity("A_DAL.Model.NhanVien", b =>
                {
                    b.HasOne("A_DAL.Model.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("IdTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("A_DAL.Model.TaiKhoan", b =>
                {
                    b.HasOne("A_DAL.Model.NhanVien", "NhanViens")
                        .WithMany()
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
